package synth

import (
	"time"

	"github.com/tetrackt/tetrackt/audio"
)

func builtinPatches() []SynthPatch {
	patches := [][]SynthPatch{
		leadPatches(),
		bassPatches(),
		padPatches(),
		arpPatches(),
		percussivePatches(),
		sfxPatches(),
		wavetablePatches(),
	}

	var joined []SynthPatch
	for _, s := range patches {
		joined = append(joined, s...)
	}

	return joined
}

func leadPatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "Square Lead", Bank: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 20 * ms, Sustain: 0.8, Release: 60 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Pulse Lead 25%", Bank: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 15 * ms, Sustain: 0.8, Release: 60 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Thin Pulse", Bank: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.125},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 15 * ms, Sustain: 0.75, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Triangle Lead", Bank: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Sustain: 1.0, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Vibrato Square", Bank: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 10 * ms, Decay: 20 * ms, Sustain: 0.8, Release: 80 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 6.0, Depth: 0.015, Delay: 0.2, Dest: audio.ModPitch},
			}},
		{Name: "Portamento Lead", Bank: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 20 * ms, Sustain: 0.8, Release: 60 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "DMG Lead", Bank: "Lead", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 30 * ms, Sustain: 0.75, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Gameboy Crush", Bank: "Lead", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 20 * ms, Sustain: 0.7, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "PWM Lead", Bank: "Lead", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 30 * ms, Sustain: 0.8, Release: 80 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOTriangle, Rate: 1.5, Depth: 0.4, Dest: audio.ModPulseWidth},
			}},
		{Name: "SID Sawtooth", Bank: "Lead", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 5 * ms, Decay: 40 * ms, Sustain: 0.7, Release: 80 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.45, Resonance: 0.3},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 80 * ms, Sustain: 0.3, Release: 80 * ms, Depth: 0.4},
			}},
		{Name: "SID Pulse Lead", Bank: "Lead", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:      audio.Envelope{Attack: 5 * ms, Decay: 30 * ms, Sustain: 0.75, Release: 100 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.35},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 60 * ms, Sustain: 0.2, Release: 100 * ms, Depth: 0.35},
			}},
		{Name: "SID Hard Lead", Bank: "Lead", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 50 * ms, Sustain: 0.6, Release: 100 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.6},
				FilterEnvelope: audio.FilterEnvelope{Attack: 3 * ms, Decay: 100 * ms, Sustain: 0.1, Release: 100 * ms, Depth: 0.5},
			}},
		{Name: "YM Lead", Bank: "Lead", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 30 * ms, Sustain: 0.8, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "AY Square Lead", Bank: "Lead", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 20 * ms, Sustain: 0.85, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Sine Lead", Bank: "Lead",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine},
				Envelope1:   audio.Envelope{Attack: 15 * ms, Decay: 40 * ms, Sustain: 0.8, Release: 150 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Detuned Lead", Bank: "Lead",
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth, Detune: -8},
				Envelope1:      audio.Envelope{Attack: 5 * ms, Decay: 40 * ms, Sustain: 0.75, Release: 120 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Sawtooth, Detune: 8},
				Envelope2:      audio.Envelope{Attack: 5 * ms, Decay: 40 * ms, Sustain: 0.75, Release: 120 * ms},
				Mixer:          audio.Mixer{Volume1: 0.6, Volume2: 0.6},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.15},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 60 * ms, Sustain: 0.2, Release: 120 * ms, Depth: 0.35},
			}},
		{Name: "Bright Saw Lead", Bank: "Lead",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 50 * ms, Sustain: 0.8, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.3, Resonance: 0.1},
			}},
		{Name: "Supersaw Lead", Bank: "Lead", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth, Detune: -15},
				Envelope1:      audio.Envelope{Attack: 5 * ms, Decay: 30 * ms, Sustain: 0.8, Release: 120 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope2:      audio.Envelope{Attack: 5 * ms, Decay: 30 * ms, Sustain: 0.8, Release: 120 * ms},
				Oscillator3:    audio.Oscillator{Type: audio.Sawtooth, Detune: 15},
				Envelope3:      audio.Envelope{Attack: 5 * ms, Decay: 30 * ms, Sustain: 0.8, Release: 120 * ms},
				Mixer:          audio.Mixer{Volume1: 0.45, Volume2: 0.55, Volume3: 0.45},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.6, Resonance: 0.2},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 60 * ms, Sustain: 0.3, Release: 120 * ms, Depth: 0.3},
			}},
		{Name: "Organ", Bank: "Lead", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine},
				Envelope1:   audio.Envelope{Attack: 8 * ms, Sustain: 1.0, Release: 30 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Sine, Detune: 1200},
				Envelope2:   audio.Envelope{Attack: 8 * ms, Sustain: 1.0, Release: 30 * ms},
				Oscillator3: audio.Oscillator{Type: audio.Sine, Detune: 1900},
				Envelope3:   audio.Envelope{Attack: 8 * ms, Sustain: 1.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 0.7, Volume2: 0.5, Volume3: 0.3},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Hollow Lead", Bank: "Lead", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 40 * ms, Sustain: 0.7, Release: 100 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Triangle, Detune: -5},
				Envelope2:      audio.Envelope{Attack: 5 * ms, Decay: 50 * ms, Sustain: 0.6, Release: 100 * ms},
				Oscillator3:    audio.Oscillator{Type: audio.Sine, Detune: 5},
				Envelope3:      audio.Envelope{Attack: 8 * ms, Decay: 60 * ms, Sustain: 0.5, Release: 120 * ms},
				Mixer:          audio.Mixer{Volume1: 0.5, Volume2: 0.4, Volume3: 0.25},
				Filter:         audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.5, Resonance: 0.25},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 80 * ms, Sustain: 0.25, Release: 100 * ms, Depth: 0.35},
			}},
		{Name: "Rasp Lead", Bank: "Lead", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 40 * ms, Sustain: 0.65, Release: 80 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope2:      audio.Envelope{Attack: 2 * ms, Decay: 40 * ms, Sustain: 0.55, Release: 80 * ms},
				Oscillator3:    audio.Oscillator{Type: audio.Noise},
				Envelope3:      audio.Envelope{Attack: 1 * ms, Decay: 15 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:          audio.Mixer{Volume1: 0.5, Volume2: 0.4, Volume3: 0.15, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.45, Resonance: 0.3},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 100 * ms, Sustain: 0.15, Release: 80 * ms, Depth: 0.45},
			}},
	}
}

func bassPatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "Triangle Bass", Bank: "Bass", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Sustain: 1.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Square Bass", Bank: "Bass", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 30 * ms, Sustain: 0.7, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Chip Bass", Bank: "Bass", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 60 * ms, Sustain: 0.5, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "NES Glide Bass", Bank: "Bass", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Sustain: 1.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "DMG Bass", Bank: "Bass", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 40 * ms, Sustain: 0.65, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Gameboy Rumble", Bank: "Bass", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 50 * ms, Sustain: 0.75, Release: 60 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 0.5, Depth: 0.3, Dest: audio.ModPulseWidth},
			}},
		{Name: "SID Bass", Bank: "Bass", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 5 * ms, Decay: 80 * ms, Sustain: 0.6, Release: 100 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.3},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 120 * ms, Sustain: 0.2, Release: 100 * ms, Depth: 0.45},
			}},
		{Name: "SID Wobble Bass", Bank: "Bass", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 50 * ms, Sustain: 0.7, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.4},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 3.0, Depth: 0.3, Dest: audio.ModCutoff},
			}},
		{Name: "SID Acid Bass", Bank: "Bass", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 120 * ms, Sustain: 0.3, Release: 80 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.2, Resonance: 0.75},
				FilterEnvelope: audio.FilterEnvelope{Attack: 3 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 80 * ms, Depth: 0.6},
			}},
		{Name: "YM Bass", Bank: "Bass", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 60 * ms, Sustain: 0.7, Release: 60 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "AY Bass", Bank: "Bass", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 50 * ms, Sustain: 0.7, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Hard Bass", Bank: "Bass",
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 80 * ms, Sustain: 0.5, Release: 60 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.25, Resonance: 0.25},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 100 * ms, Sustain: 0.15, Release: 60 * ms, Depth: 0.4},
			}},
		{Name: "Growl Bass", Bank: "Bass",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 60 * ms, Sustain: 0.6, Release: 80 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.4, Resonance: 0.5},
			}},
		{Name: "Sub Bass", Bank: "Bass", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine},
				Envelope1:   audio.Envelope{Attack: 10 * ms, Decay: 100 * ms, Sustain: 0.8, Release: 200 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Moog Bass", Bank: "Bass", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 5 * ms, Decay: 150 * ms, Sustain: 0.4, Release: 200 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.5},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 200 * ms, Sustain: 0.1, Release: 200 * ms, Depth: 0.5},
			}},
		{Name: "Acid Techno", Bank: "Bass", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 200 * ms, Sustain: 0.2, Release: 100 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.2, Resonance: 0.8},
				FilterEnvelope: audio.FilterEnvelope{Attack: 3 * ms, Decay: 250 * ms, Sustain: 0.0, Release: 100 * ms, Depth: 0.65},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 2.0, Depth: 0.15, Dest: audio.ModCutoff},
			}},
		{Name: "Triple Stack Bass", Bank: "Bass", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 8 * ms, Decay: 120 * ms, Sustain: 0.7, Release: 200 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Sawtooth, Detune: -10},
				Envelope2:      audio.Envelope{Attack: 5 * ms, Decay: 100 * ms, Sustain: 0.6, Release: 150 * ms},
				Oscillator3:    audio.Oscillator{Type: audio.Square, PulseWidth: 0.5, Detune: 10},
				Envelope3:      audio.Envelope{Attack: 5 * ms, Decay: 80 * ms, Sustain: 0.4, Release: 120 * ms},
				Mixer:          audio.Mixer{Volume1: 0.6, Volume2: 0.45, Volume3: 0.3},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.35, Resonance: 0.35},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 150 * ms, Sustain: 0.1, Release: 150 * ms, Depth: 0.5},
			}},
		{Name: "Reese Bass", Bank: "Bass", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth, Detune: -7},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 80 * ms, Sustain: 0.8, Release: 150 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Sawtooth, Detune: 7},
				Envelope2:   audio.Envelope{Attack: 5 * ms, Decay: 80 * ms, Sustain: 0.8, Release: 150 * ms},
				Oscillator3: audio.Oscillator{Type: audio.Sine},
				Envelope3:   audio.Envelope{Attack: 8 * ms, Decay: 100 * ms, Sustain: 0.9, Release: 200 * ms},
				Mixer:       audio.Mixer{Volume1: 0.5, Volume2: 0.5, Volume3: 0.4, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.4, Resonance: 0.45},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 1.5, Depth: 0.2, Dest: audio.ModCutoff},
			}},
		{Name: "Power Chord Bass", Bank: "Bass", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 60 * ms, Sustain: 0.75, Release: 60 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope2:   audio.Envelope{Attack: 3 * ms, Decay: 50 * ms, Sustain: 0.6, Release: 50 * ms},
				Oscillator3: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope3:   audio.Envelope{Attack: 2 * ms, Decay: 40 * ms, Sustain: 0.5, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 0.65, Volume2: 0.5, Volume3: 0.4, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
	}
}

func padPatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "Tri Pad", Bank: "Pad", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 60 * ms, Sustain: 1.0, Release: 200 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Pulse Pad", Bank: "Pad", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 80 * ms, Decay: 40 * ms, Sustain: 0.85, Release: 200 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "NES Chord", Bank: "Pad", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 40 * ms, Sustain: 0.9, Release: 150 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope2:   audio.Envelope{Attack: 40 * ms, Sustain: 0.7, Release: 150 * ms},
				Mixer:       audio.Mixer{Volume1: 0.7, Volume2: 0.5, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Gameboy Pad", Bank: "Pad", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 50 * ms, Decay: 30 * ms, Sustain: 0.8, Release: 150 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Retro Pad", Bank: "Pad", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 100 * ms, Sustain: 1.0, Release: 300 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 0.3, Depth: 0.02, Delay: 0.5, Dest: audio.ModPitch},
			}},
		{Name: "SID Pad", Bank: "Pad", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 60 * ms, Decay: 60 * ms, Sustain: 0.7, Release: 200 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.4, Resonance: 0.2},
				FilterEnvelope: audio.FilterEnvelope{Attack: 80 * ms, Decay: 150 * ms, Sustain: 0.3, Release: 200 * ms, Depth: 0.35},
			}},
		{Name: "SID Atmosphere", Bank: "Pad", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 120 * ms, Decay: 80 * ms, Sustain: 0.6, Release: 400 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.3},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 0.4, Depth: 0.25, Dest: audio.ModCutoff},
			}},
		{Name: "SID Detune Pad", Bank: "Pad", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth, Detune: -10},
				Envelope1:   audio.Envelope{Attack: 80 * ms, Decay: 60 * ms, Sustain: 0.7, Release: 300 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Sawtooth, Detune: 10},
				Envelope2:   audio.Envelope{Attack: 80 * ms, Decay: 60 * ms, Sustain: 0.7, Release: 300 * ms},
				Mixer:       audio.Mixer{Volume1: 0.6, Volume2: 0.6, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.6, Resonance: 0.2},
			}},
		{Name: "Arcade Pad", Bank: "Pad", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 40 * ms, Decay: 50 * ms, Sustain: 0.75, Release: 150 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "PWM Pad", Bank: "Pad",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 80 * ms, Decay: 50 * ms, Sustain: 0.8, Release: 250 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOTriangle, Rate: 0.8, Depth: 0.5, Dest: audio.ModPulseWidth},
			}},
		{Name: "Space Wash", Bank: "Pad",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 150 * ms, Decay: 80 * ms, Sustain: 0.7, Release: 400 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 0.25, Depth: 0.4, Dest: audio.ModVolume},
			}},
		{Name: "String Ensemble", Bank: "Pad", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth, Detune: -12},
				Envelope1:      audio.Envelope{Attack: 80 * ms, Decay: 60 * ms, Sustain: 0.75, Release: 400 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Sawtooth, Detune: 12},
				Envelope2:      audio.Envelope{Attack: 80 * ms, Decay: 60 * ms, Sustain: 0.75, Release: 400 * ms},
				Oscillator3:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope3:      audio.Envelope{Attack: 80 * ms, Decay: 60 * ms, Sustain: 0.75, Release: 400 * ms},
				Mixer:          audio.Mixer{Volume1: 0.4, Volume2: 0.4, Volume3: 0.4},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.55, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 100 * ms, Decay: 200 * ms, Sustain: 0.4, Release: 400 * ms, Depth: 0.3},
			}},
		{Name: "Warm Synth Pad", Bank: "Pad", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Triangle},
				Envelope1:      audio.Envelope{Attack: 200 * ms, Decay: 100 * ms, Sustain: 0.8, Release: 600 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.45, Resonance: 0.05},
				FilterEnvelope: audio.FilterEnvelope{Attack: 250 * ms, Decay: 300 * ms, Sustain: 0.4, Release: 600 * ms, Depth: 0.35},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 0.3, Depth: 0.1, Delay: 0.5, Dest: audio.ModVolume},
			}},
		{Name: "Shimmer Pad", Bank: "Pad", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth, Detune: -5},
				Envelope1:      audio.Envelope{Attack: 150 * ms, Decay: 100 * ms, Sustain: 0.7, Release: 500 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Sawtooth, Detune: 5},
				Envelope2:      audio.Envelope{Attack: 150 * ms, Decay: 100 * ms, Sustain: 0.7, Release: 500 * ms},
				Mixer:          audio.Mixer{Volume1: 0.6, Volume2: 0.6},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.15},
				FilterEnvelope: audio.FilterEnvelope{Attack: 200 * ms, Decay: 250 * ms, Sustain: 0.35, Release: 500 * ms, Depth: 0.35},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 0.5, Depth: 0.15, Dest: audio.ModPitch},
			}},
		{Name: "Dream Pad", Bank: "Pad",
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 120 * ms, Decay: 80 * ms, Sustain: 0.9, Release: 500 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Triangle},
				Envelope2:      audio.Envelope{Attack: 120 * ms, Decay: 80 * ms, Sustain: 0.7, Release: 500 * ms},
				Mixer:          audio.Mixer{Volume1: 0.6, Volume2: 0.5},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.45, Resonance: 0.05},
				FilterEnvelope: audio.FilterEnvelope{Attack: 150 * ms, Decay: 200 * ms, Sustain: 0.5, Release: 500 * ms, Depth: 0.35},
			}},
		{Name: "Lush Pad", Bank: "Pad", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth, Detune: -20},
				Envelope1:      audio.Envelope{Attack: 200 * ms, Decay: 80 * ms, Sustain: 0.8, Release: 600 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope2:      audio.Envelope{Attack: 200 * ms, Decay: 80 * ms, Sustain: 0.8, Release: 600 * ms},
				Oscillator3:    audio.Oscillator{Type: audio.Sawtooth, Detune: 20},
				Envelope3:      audio.Envelope{Attack: 200 * ms, Decay: 80 * ms, Sustain: 0.8, Release: 600 * ms},
				Mixer:          audio.Mixer{Volume1: 0.4, Volume2: 0.5, Volume3: 0.4},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.05},
				FilterEnvelope: audio.FilterEnvelope{Attack: 250 * ms, Decay: 300 * ms, Sustain: 0.45, Release: 600 * ms, Depth: 0.3},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 0.2, Depth: 0.12, Dest: audio.ModCutoff},
			}},
		{Name: "Choir Pad", Bank: "Pad", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine, Detune: -6},
				Envelope1:   audio.Envelope{Attack: 180 * ms, Decay: 100 * ms, Sustain: 0.85, Release: 500 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Triangle},
				Envelope2:   audio.Envelope{Attack: 150 * ms, Decay: 100 * ms, Sustain: 0.9, Release: 500 * ms},
				Oscillator3: audio.Oscillator{Type: audio.Sine, Detune: 6},
				Envelope3:   audio.Envelope{Attack: 180 * ms, Decay: 100 * ms, Sustain: 0.85, Release: 500 * ms},
				Mixer:       audio.Mixer{Volume1: 0.45, Volume2: 0.6, Volume3: 0.45},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.55, Resonance: 0.05},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 0.35, Depth: 0.008, Delay: 0.6, Dest: audio.ModPitch},
			}},
	}
}

func arpPatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "Chip Arp", Bank: "Arp", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 30 * ms, Sustain: 0.7, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Tri Arp", Bank: "Arp", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 40 * ms, Sustain: 0.8, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Pulse Arp 25%", Bank: "Arp", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 25 * ms, Sustain: 0.7, Release: 15 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "DMG Arp", Bank: "Arp", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 35 * ms, Sustain: 0.65, Release: 15 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "GB Fast Arp", Bank: "Arp", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 20 * ms, Sustain: 0.5, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "SID Arp", Bank: "Arp", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 50 * ms, Sustain: 0.5, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.6, Resonance: 0.3},
			}},
		{Name: "SID Hard Arp", Bank: "Arp", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 40 * ms, Sustain: 0.6, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.55, Resonance: 0.5},
			}},
		{Name: "YM Arp", Bank: "Arp", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.6, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Pluck Arp", Bank: "Arp",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Bell Arp", Bank: "Arp",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 120 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Bubble Arp", Bank: "Arp",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 60 * ms, Sustain: 0.3, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.6, Resonance: 0.4},
			}},
		{Name: "Crystal Arp", Bank: "Arp",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.65, Resonance: 0.3},
			}},
		{Name: "String Arp", Bank: "Arp", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth, Detune: -6},
				Envelope1:   audio.Envelope{Attack: 10 * ms, Decay: 60 * ms, Sustain: 0.4, Release: 40 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Sawtooth, Detune: 6},
				Envelope2:   audio.Envelope{Attack: 10 * ms, Decay: 60 * ms, Sustain: 0.4, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 0.6, Volume2: 0.6},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.7, Resonance: 0.1},
			}},
		{Name: "Harp Arp", Bank: "Arp", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Piano Arp", Bank: "Arp", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 150 * ms, Sustain: 0.2, Release: 50 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Sine},
				Envelope2:   audio.Envelope{Attack: 3 * ms, Decay: 120 * ms, Sustain: 0.1, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 0.7, Volume2: 0.4},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Triple Chip Arp", Bank: "Arp", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.6, Release: 15 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 35 * ms, Sustain: 0.5, Release: 12 * ms},
				Oscillator3: audio.Oscillator{Type: audio.Triangle},
				Envelope3:   audio.Envelope{Attack: 2 * ms, Decay: 50 * ms, Sustain: 0.65, Release: 15 * ms},
				Mixer:       audio.Mixer{Volume1: 0.5, Volume2: 0.4, Volume3: 0.45, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Fat Arp", Bank: "Arp", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth, Detune: -8},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 60 * ms, Sustain: 0.45, Release: 30 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Sawtooth, Detune: 8},
				Envelope2:      audio.Envelope{Attack: 3 * ms, Decay: 60 * ms, Sustain: 0.45, Release: 30 * ms},
				Oscillator3:    audio.Oscillator{Type: audio.Sine},
				Envelope3:      audio.Envelope{Attack: 5 * ms, Decay: 80 * ms, Sustain: 0.5, Release: 40 * ms},
				Mixer:          audio.Mixer{Volume1: 0.5, Volume2: 0.5, Volume3: 0.35},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.55, Resonance: 0.2},
				FilterEnvelope: audio.FilterEnvelope{Attack: 3 * ms, Decay: 80 * ms, Sustain: 0.2, Release: 30 * ms, Depth: 0.4},
			}},
	}
}

func percussivePatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "NES Kick", Bank: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Triangle},
				Envelope1:      audio.Envelope{Attack: 1 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 1 * ms, Decay: 50 * ms, Sustain: 0.0, Release: 20 * ms, Depth: 0.55},
			}},
		{Name: "NES Snare", Bank: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 120 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "NES Hi-Hat", Bank: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 30 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "NES Crash", Bank: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 500 * ms, Sustain: 0.0, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Triangle Tom", Bank: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Noise Tom", Bank: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.2},
			}},
		{Name: "Gameboy Kick", Bank: "Percussive", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 60 * ms, Sustain: 0.0, Release: 10 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Triangle},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 0.6, Volume2: 0.8},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Gameboy Snare", Bank: "Percussive", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 15 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Gameboy Hi-Hat", Bank: "Percussive", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 20 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "SID Noise Hit", Bank: "Percussive", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.4, Resonance: 0.3},
			}},
		{Name: "Arcade Hit", Bank: "Percussive", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.2},
			}},
		{Name: "Clap", Bank: "Percussive",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.45, Resonance: 0.2},
			}},
		{Name: "Metallic", Bank: "Percussive",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.55, Resonance: 0.4},
			}},
		{Name: "Sub Kick", Bank: "Percussive", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 30 * ms, Depth: 0.5},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 0.8, Depth: 0.8, Dest: audio.ModPitch},
			}},
		{Name: "808 Kick", Bank: "Percussive", Tags: []string{"Analog", "808"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 400 * ms, Sustain: 0.0, Release: 50 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.25, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 50 * ms, Depth: 0.55},
			}},
		{Name: "Snare", Bank: "Percussive", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 30 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Triangle},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 50 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 0.7, Volume2: 0.4},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.35, Resonance: 0.1},
			}},
		{Name: "808 Snare", Bank: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Noise},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 30 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Triangle},
				Envelope2:      audio.Envelope{Attack: 1 * ms, Decay: 60 * ms, Sustain: 0.0, Release: 15 * ms},
				Mixer:          audio.Mixer{Volume1: 0.8, Volume2: 0.5},
				Filter:         audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.35, Resonance: 0.2},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 60 * ms, Sustain: 0.0, Release: 30 * ms, Depth: 0.4},
			}},
		{Name: "808 Closed Hat", Bank: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.0, Release: 8 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.65, Resonance: 0.1},
			}},
		{Name: "808 Open Hat", Bank: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 400 * ms, Sustain: 0.0, Release: 60 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Noise},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 0.8, Volume2: 0.3},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.6, Resonance: 0.1},
			}},
		{Name: "808 Tom", Bank: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 500 * ms, Sustain: 0.0, Release: 50 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 50 * ms, Depth: 0.5},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 2.5, Depth: 0.6, Dest: audio.ModPitch},
			}},
		{Name: "808 Cowbell", Bank: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5, Detune: -15},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 250 * ms, Sustain: 0.0, Release: 30 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5, Detune: 15},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 250 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 0.6, Volume2: 0.6},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.62, Resonance: 0.5},
			}},
		{Name: "808 Clap", Bank: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Noise},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.4, Resonance: 0.2},
				FilterEnvelope: audio.FilterEnvelope{Attack: 3 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 30 * ms, Depth: 0.35},
			}},
		{Name: "808 Cymbal", Bank: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 800 * ms, Sustain: 0.0, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.55, Resonance: 0.15},
			}},
		{Name: "909 Kick", Bank: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 220 * ms, Sustain: 0.0, Release: 30 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Noise},
				Envelope2:      audio.Envelope{Attack: 1 * ms, Decay: 25 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:          audio.Mixer{Volume1: 0.9, Volume2: 0.5},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.35, Resonance: 0.15},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 30 * ms, Depth: 0.5},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 5.0, Depth: 0.6, Dest: audio.ModPitch},
			}},
		{Name: "909 Snare", Bank: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Noise},
				Envelope1:      audio.Envelope{Attack: 1 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 20 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Triangle},
				Envelope2:      audio.Envelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:          audio.Mixer{Volume1: 0.8, Volume2: 0.6},
				Filter:         audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.45, Resonance: 0.3},
				FilterEnvelope: audio.FilterEnvelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.0, Release: 20 * ms, Depth: 0.45},
			}},
		{Name: "909 Closed Hat", Bank: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 15 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.75, Resonance: 0.1},
			}},
		{Name: "909 Open Hat", Bank: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 250 * ms, Sustain: 0.0, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.72, Resonance: 0.1},
			}},
		{Name: "909 Clap", Bank: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Noise},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.5, Resonance: 0.25},
				FilterEnvelope: audio.FilterEnvelope{Attack: 3 * ms, Decay: 50 * ms, Sustain: 0.0, Release: 20 * ms, Depth: 0.4},
			}},
		{Name: "909 Tom", Bank: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 300 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.4, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 70 * ms, Sustain: 0.0, Release: 30 * ms, Depth: 0.45},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 4.0, Depth: 0.5, Dest: audio.ModPitch},
			}},
		{Name: "909 Cymbal", Bank: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 700 * ms, Sustain: 0.0, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.6, Resonance: 0.15},
			}},
		{Name: "909 Rim", Bank: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 50 * ms, Sustain: 0.0, Release: 8 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Sine},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 20 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:       audio.Mixer{Volume1: 0.7, Volume2: 0.4},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.65, Resonance: 0.3},
			}},
		{Name: "Full Kick", Bank: "Percussive", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 350 * ms, Sustain: 0.0, Release: 40 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Noise},
				Envelope2:      audio.Envelope{Attack: 1 * ms, Decay: 18 * ms, Sustain: 0.0, Release: 5 * ms},
				Oscillator3:    audio.Oscillator{Type: audio.Triangle},
				Envelope3:      audio.Envelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.0, Release: 8 * ms},
				Mixer:          audio.Mixer{Volume1: 0.9, Volume2: 0.5, Volume3: 0.35},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 40 * ms, Depth: 0.55},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 4.0, Depth: 0.65, Dest: audio.ModPitch},
			}},
		{Name: "Fat Snare", Bank: "Percussive", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 180 * ms, Sustain: 0.0, Release: 30 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Triangle},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 55 * ms, Sustain: 0.0, Release: 10 * ms},
				Oscillator3: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope3:   audio.Envelope{Attack: 1 * ms, Decay: 25 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:       audio.Mixer{Volume1: 0.7, Volume2: 0.45, Volume3: 0.4},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.3, Resonance: 0.15},
			}},
	}
}

func sfxPatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "Power Up", Bank: "SFX", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 300 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSawtooth, Rate: 8.0, Depth: 0.5, Dest: audio.ModPitch},
			}},
		{Name: "Coin", Bank: "SFX", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Jump", Bank: "SFX", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 12.0, Depth: 0.3, Dest: audio.ModPitch},
			}},
		{Name: "Explosion", Bank: "SFX", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Noise},
				Envelope1:      audio.Envelope{Attack: 1 * ms, Decay: 400 * ms, Sustain: 0.0, Release: 50 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.2, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 1 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 50 * ms, Depth: 0.5},
			}},
		{Name: "SID Laser", Bank: "SFX", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 1 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.4, Resonance: 0.3},
				FilterEnvelope: audio.FilterEnvelope{Attack: 1 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 20 * ms, Depth: 0.55},
				LFO1:           audio.LFO{Waveform: audio.LFOSawtooth, Rate: 10.0, Depth: 0.6, Dest: audio.ModPitch},
			}},
		{Name: "SID Zap", Bank: "SFX", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 15 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.55, Resonance: 0.5},
			}},
		{Name: "Arcade Beep", Bank: "SFX", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 60 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "UFO", Bank: "SFX", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 20 * ms, Decay: 50 * ms, Sustain: 0.8, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 15.0, Depth: 0.15, Dest: audio.ModPitch},
			}},
		{Name: "Sweep Up", Bank: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 300 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSawtooth, Rate: 5.0, Depth: 0.4, Dest: audio.ModPitch},
			}},
		{Name: "Alarm", Bank: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Sustain: 0.8, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSquare, Rate: 4.0, Depth: 0.8, Dest: audio.ModVolume},
			}},
		{Name: "Blip", Bank: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "White Noise", Bank: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 10 * ms, Sustain: 0.8, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Static Buzz", Bank: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Sustain: 0.7, Release: 80 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.5, Resonance: 0.1},
			}},
		{Name: "Glitch Hit", Bank: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 120 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.3},
			}},
		{Name: "Wobble SFX", Bank: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.6, Resonance: 0.4},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 8.0, Depth: 0.4, Dest: audio.ModCutoff},
			}},
		{Name: "Triple Alarm", Bank: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Sustain: 0.8, Release: 30 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Sawtooth, Detune: -10},
				Envelope2:   audio.Envelope{Attack: 3 * ms, Sustain: 0.6, Release: 30 * ms},
				Oscillator3: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25, Detune: 10},
				Envelope3:   audio.Envelope{Attack: 3 * ms, Sustain: 0.5, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 0.45, Volume2: 0.35, Volume3: 0.3, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSquare, Rate: 3.0, Depth: 0.9, Dest: audio.ModVolume},
			}},
	}
}

func wavetablePatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "WT Flute", Bank: "Wavetable", Tags: []string{"AKWF"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{
					Type:      audio.Wavetable,
					Wavetable: resolveWavetable("akwf:AKWF_flute/AKWF_flute_0001"),
					Meta:      resolveWavetableMeta("akwf:AKWF_flute/AKWF_flute_0001"),
				},
				Envelope1: audio.Envelope{Attack: 20 * ms, Decay: 30 * ms, Sustain: 0.85, Release: 200 * ms},
				Mixer:     audio.Mixer{Volume1: 1.0},
				Filter:    audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "WT E-Piano", Bank: "Wavetable", Tags: []string{"AKWF"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{
					Type:      audio.Wavetable,
					Wavetable: resolveWavetable("akwf:AKWF_epiano/AKWF_epiano_0001"),
					Meta:      resolveWavetableMeta("akwf:AKWF_epiano/AKWF_epiano_0001"),
				},
				Envelope1: audio.Envelope{Attack: 5 * ms, Decay: 200 * ms, Sustain: 0.4, Release: 300 * ms},
				Mixer:     audio.Mixer{Volume1: 1.0},
				Filter:    audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "WT E-Organ", Bank: "Wavetable", Tags: []string{"AKWF"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{
					Type:      audio.Wavetable,
					Wavetable: resolveWavetable("akwf:AKWF_eorgan/AKWF_eorgan_0001"),
					Meta:      resolveWavetableMeta("akwf:AKWF_eorgan/AKWF_eorgan_0001"),
				},
				Envelope1: audio.Envelope{Attack: 10 * ms, Sustain: 1.0, Release: 50 * ms},
				Mixer:     audio.Mixer{Volume1: 1.0},
				Filter:    audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "WT Violin", Bank: "Wavetable", Tags: []string{"AKWF"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{
					Type:      audio.Wavetable,
					Wavetable: resolveWavetable("akwf:AKWF_violin/AKWF_violin_0001"),
					Meta:      resolveWavetableMeta("akwf:AKWF_violin/AKWF_violin_0001"),
				},
				Envelope1: audio.Envelope{Attack: 60 * ms, Sustain: 0.9, Release: 200 * ms},
				Mixer:     audio.Mixer{Volume1: 1.0},
				Filter:    audio.Filter{Type: audio.FilterOff},
				LFO1:      audio.LFO{Waveform: audio.LFOSine, Rate: 5.5, Depth: 0.012, Delay: 0.3, Dest: audio.ModPitch},
			}},
		{Name: "WT Cello", Bank: "Wavetable", Tags: []string{"AKWF"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{
					Type:      audio.Wavetable,
					Wavetable: resolveWavetable("akwf:AKWF_cello/AKWF_cello_0001"),
					Meta:      resolveWavetableMeta("akwf:AKWF_cello/AKWF_cello_0001"),
				},
				Envelope1: audio.Envelope{Attack: 80 * ms, Sustain: 0.85, Release: 300 * ms},
				Mixer:     audio.Mixer{Volume1: 1.0},
				Filter:    audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.6, Resonance: 0.1},
			}},
		{Name: "WT Human Voice", Bank: "Wavetable", Tags: []string{"AKWF"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{
					Type:      audio.Wavetable,
					Wavetable: resolveWavetable("akwf:AKWF_hvoice/AKWF_hvoice_0001"),
					Meta:      resolveWavetableMeta("akwf:AKWF_hvoice/AKWF_hvoice_0001"),
				},
				Envelope1: audio.Envelope{Attack: 40 * ms, Sustain: 0.9, Release: 200 * ms},
				Mixer:     audio.Mixer{Volume1: 1.0},
				Filter:    audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "WT Soft Saw", Bank: "Wavetable", Tags: []string{"AKWF"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{
					Type:      audio.Wavetable,
					Wavetable: resolveWavetable("akwf:AKWF_bw_saw/AKWF_bw_saw_0001"),
					Meta:      resolveWavetableMeta("akwf:AKWF_bw_saw/AKWF_bw_saw_0001"),
				},
				Envelope1: audio.Envelope{Attack: 5 * ms, Decay: 40 * ms, Sustain: 0.8, Release: 100 * ms},
				Mixer:     audio.Mixer{Volume1: 1.0},
				Filter:    audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.15},
			}},
		{Name: "WT FM Synth", Bank: "Wavetable", Tags: []string{"AKWF"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{
					Type:      audio.Wavetable,
					Wavetable: resolveWavetable("akwf:AKWF_fmsynth/AKWF_fmsynth_0001"),
					Meta:      resolveWavetableMeta("akwf:AKWF_fmsynth/AKWF_fmsynth_0001"),
				},
				Envelope1: audio.Envelope{Attack: 3 * ms, Decay: 60 * ms, Sustain: 0.7, Release: 80 * ms},
				Mixer:     audio.Mixer{Volume1: 1.0},
				Filter:    audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "WT Vgame Lead", Bank: "Wavetable", Tags: []string{"AKWF"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{
					Type:      audio.Wavetable,
					Wavetable: resolveWavetable("akwf:AKWF_vgame/AKWF_vgame_0001"),
					Meta:      resolveWavetableMeta("akwf:AKWF_vgame/AKWF_vgame_0001"),
				},
				Envelope1: audio.Envelope{Attack: 2 * ms, Decay: 20 * ms, Sustain: 0.8, Release: 60 * ms},
				Mixer:     audio.Mixer{Volume1: 1.0},
				Filter:    audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "WT Acoustic Guitar", Bank: "Wavetable", Tags: []string{"AKWF"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{
					Type:      audio.Wavetable,
					Wavetable: resolveWavetable("akwf:AKWF_aguitar/AKWF_aguitar_0001"),
					Meta:      resolveWavetableMeta("akwf:AKWF_aguitar/AKWF_aguitar_0001"),
				},
				Envelope1: audio.Envelope{Attack: 3 * ms, Decay: 300 * ms, Sustain: 0.2, Release: 400 * ms},
				Mixer:     audio.Mixer{Volume1: 1.0},
				Filter:    audio.Filter{Type: audio.FilterOff},
			}},
	}
}
