package synth

import (
	"time"

	"github.com/tetrackt/tetrackt/audio"
)

func builtinPatches() []SynthPatch {
	patches := [][]SynthPatch{
		leadPatches(),
		bassPatches(),
		padPatches(),
		arpPatches(),
		percussivePatches(),
		sfxPatches(),
	}

	var joined []SynthPatch
	for _, s := range patches {
		joined = append(joined, s...)
	}

	return joined
}

func leadPatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "Square Lead", Category: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 20 * ms, Sustain: 0.8, Release: 60 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Pulse Lead 25%", Category: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 15 * ms, Sustain: 0.8, Release: 60 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Thin Pulse", Category: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.125},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 15 * ms, Sustain: 0.75, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Triangle Lead", Category: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Sustain: 1.0, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Vibrato Square", Category: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 10 * ms, Decay: 20 * ms, Sustain: 0.8, Release: 80 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 6.0, Depth: 0.015, Delay: 0.2, Dest: audio.ModPitch},
			}},
		{Name: "Portamento Lead", Category: "Lead", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 20 * ms, Sustain: 0.8, Release: 60 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
				Portamento:  0.04,
			}},
		{Name: "DMG Lead", Category: "Lead", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 30 * ms, Sustain: 0.75, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Gameboy Crush", Category: "Lead", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 20 * ms, Sustain: 0.7, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "PWM Lead", Category: "Lead", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 30 * ms, Sustain: 0.8, Release: 80 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOTriangle, Rate: 1.5, Depth: 0.4, Dest: audio.ModPulseWidth},
			}},
		{Name: "SID Sawtooth", Category: "Lead", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 5 * ms, Decay: 40 * ms, Sustain: 0.7, Release: 80 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.45, Resonance: 0.3},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 80 * ms, Sustain: 0.3, Release: 80 * ms, Depth: 0.4},
			}},
		{Name: "SID Pulse Lead", Category: "Lead", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:      audio.Envelope{Attack: 5 * ms, Decay: 30 * ms, Sustain: 0.75, Release: 100 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.35},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 60 * ms, Sustain: 0.2, Release: 100 * ms, Depth: 0.35},
			}},
		{Name: "SID Hard Lead", Category: "Lead", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 50 * ms, Sustain: 0.6, Release: 100 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.6},
				FilterEnvelope: audio.FilterEnvelope{Attack: 3 * ms, Decay: 100 * ms, Sustain: 0.1, Release: 100 * ms, Depth: 0.5},
			}},
		{Name: "YM Lead", Category: "Lead", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 30 * ms, Sustain: 0.8, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "AY Square Lead", Category: "Lead", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 20 * ms, Sustain: 0.85, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Sine Lead", Category: "Lead",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine},
				Envelope1:   audio.Envelope{Attack: 15 * ms, Decay: 40 * ms, Sustain: 0.8, Release: 150 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Detuned Lead", Category: "Lead",
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth, Detune: -8},
				Envelope1:      audio.Envelope{Attack: 5 * ms, Decay: 40 * ms, Sustain: 0.75, Release: 120 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Sawtooth, Detune: 8},
				Envelope2:      audio.Envelope{Attack: 5 * ms, Decay: 40 * ms, Sustain: 0.75, Release: 120 * ms},
				Mixer:          audio.Mixer{Volume1: 0.6, Volume2: 0.6},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.15},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 60 * ms, Sustain: 0.2, Release: 120 * ms, Depth: 0.35},
			}},
		{Name: "Bright Saw Lead", Category: "Lead",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 50 * ms, Sustain: 0.8, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.3, Resonance: 0.1},
			}},
	}
}

func bassPatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "Triangle Bass", Category: "Bass", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Sustain: 1.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Square Bass", Category: "Bass", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 30 * ms, Sustain: 0.7, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Chip Bass", Category: "Bass", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 60 * ms, Sustain: 0.5, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "NES Glide Bass", Category: "Bass", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Sustain: 1.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
				Portamento:  0.06,
			}},
		{Name: "DMG Bass", Category: "Bass", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 40 * ms, Sustain: 0.65, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Gameboy Rumble", Category: "Bass", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 50 * ms, Sustain: 0.75, Release: 60 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 0.5, Depth: 0.3, Dest: audio.ModPulseWidth},
			}},
		{Name: "SID Bass", Category: "Bass", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 5 * ms, Decay: 80 * ms, Sustain: 0.6, Release: 100 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.3},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 120 * ms, Sustain: 0.2, Release: 100 * ms, Depth: 0.45},
			}},
		{Name: "SID Wobble Bass", Category: "Bass", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 50 * ms, Sustain: 0.7, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.4},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 3.0, Depth: 0.3, Dest: audio.ModCutoff},
			}},
		{Name: "SID Acid Bass", Category: "Bass", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 120 * ms, Sustain: 0.3, Release: 80 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.2, Resonance: 0.75},
				FilterEnvelope: audio.FilterEnvelope{Attack: 3 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 80 * ms, Depth: 0.6},
			}},
		{Name: "YM Bass", Category: "Bass", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 60 * ms, Sustain: 0.7, Release: 60 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "AY Bass", Category: "Bass", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 50 * ms, Sustain: 0.7, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Hard Bass", Category: "Bass",
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 80 * ms, Sustain: 0.5, Release: 60 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.25, Resonance: 0.25},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 100 * ms, Sustain: 0.15, Release: 60 * ms, Depth: 0.4},
			}},
		{Name: "Growl Bass", Category: "Bass",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 60 * ms, Sustain: 0.6, Release: 80 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.4, Resonance: 0.5},
			}},
		{Name: "Sub Bass", Category: "Bass", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine},
				Envelope1:   audio.Envelope{Attack: 10 * ms, Decay: 100 * ms, Sustain: 0.8, Release: 200 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Moog Bass", Category: "Bass", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 5 * ms, Decay: 150 * ms, Sustain: 0.4, Release: 200 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.5},
				FilterEnvelope: audio.FilterEnvelope{Attack: 5 * ms, Decay: 200 * ms, Sustain: 0.1, Release: 200 * ms, Depth: 0.5},
				Portamento:     0.05,
			}},
		{Name: "Acid Techno", Category: "Bass", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 200 * ms, Sustain: 0.2, Release: 100 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.2, Resonance: 0.8},
				FilterEnvelope: audio.FilterEnvelope{Attack: 3 * ms, Decay: 250 * ms, Sustain: 0.0, Release: 100 * ms, Depth: 0.65},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 2.0, Depth: 0.15, Dest: audio.ModCutoff},
			}},
	}
}

func padPatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "Tri Pad", Category: "Pad", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 60 * ms, Sustain: 1.0, Release: 200 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Pulse Pad", Category: "Pad", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 80 * ms, Decay: 40 * ms, Sustain: 0.85, Release: 200 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "NES Chord", Category: "Pad", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 40 * ms, Sustain: 0.9, Release: 150 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope2:   audio.Envelope{Attack: 40 * ms, Sustain: 0.7, Release: 150 * ms},
				Mixer:       audio.Mixer{Volume1: 0.7, Volume2: 0.5, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Gameboy Pad", Category: "Pad", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 50 * ms, Decay: 30 * ms, Sustain: 0.8, Release: 150 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Retro Pad", Category: "Pad", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 100 * ms, Sustain: 1.0, Release: 300 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 0.3, Depth: 0.02, Delay: 0.5, Dest: audio.ModPitch},
			}},
		{Name: "SID Pad", Category: "Pad", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 60 * ms, Decay: 60 * ms, Sustain: 0.7, Release: 200 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.4, Resonance: 0.2},
				FilterEnvelope: audio.FilterEnvelope{Attack: 80 * ms, Decay: 150 * ms, Sustain: 0.3, Release: 200 * ms, Depth: 0.35},
			}},
		{Name: "SID Atmosphere", Category: "Pad", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 120 * ms, Decay: 80 * ms, Sustain: 0.6, Release: 400 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.3},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 0.4, Depth: 0.25, Dest: audio.ModCutoff},
			}},
		{Name: "SID Detune Pad", Category: "Pad", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth, Detune: -10},
				Envelope1:   audio.Envelope{Attack: 80 * ms, Decay: 60 * ms, Sustain: 0.7, Release: 300 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Sawtooth, Detune: 10},
				Envelope2:   audio.Envelope{Attack: 80 * ms, Decay: 60 * ms, Sustain: 0.7, Release: 300 * ms},
				Mixer:       audio.Mixer{Volume1: 0.6, Volume2: 0.6, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.6, Resonance: 0.2},
			}},
		{Name: "Arcade Pad", Category: "Pad", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 40 * ms, Decay: 50 * ms, Sustain: 0.75, Release: 150 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "PWM Pad", Category: "Pad",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 80 * ms, Decay: 50 * ms, Sustain: 0.8, Release: 250 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOTriangle, Rate: 0.8, Depth: 0.5, Dest: audio.ModPulseWidth},
			}},
		{Name: "Space Wash", Category: "Pad",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 150 * ms, Decay: 80 * ms, Sustain: 0.7, Release: 400 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 0.25, Depth: 0.4, Dest: audio.ModVolume},
			}},
		{Name: "String Ensemble", Category: "Pad", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth, Detune: -12},
				Envelope1:      audio.Envelope{Attack: 80 * ms, Decay: 60 * ms, Sustain: 0.75, Release: 400 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Sawtooth, Detune: 12},
				Envelope2:      audio.Envelope{Attack: 80 * ms, Decay: 60 * ms, Sustain: 0.75, Release: 400 * ms},
				Oscillator3:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope3:      audio.Envelope{Attack: 80 * ms, Decay: 60 * ms, Sustain: 0.75, Release: 400 * ms},
				Mixer:          audio.Mixer{Volume1: 0.4, Volume2: 0.4, Volume3: 0.4},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.55, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 100 * ms, Decay: 200 * ms, Sustain: 0.4, Release: 400 * ms, Depth: 0.3},
			}},
		{Name: "Warm Synth Pad", Category: "Pad", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Triangle},
				Envelope1:      audio.Envelope{Attack: 200 * ms, Decay: 100 * ms, Sustain: 0.8, Release: 600 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.45, Resonance: 0.05},
				FilterEnvelope: audio.FilterEnvelope{Attack: 250 * ms, Decay: 300 * ms, Sustain: 0.4, Release: 600 * ms, Depth: 0.35},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 0.3, Depth: 0.1, Delay: 0.5, Dest: audio.ModVolume},
			}},
		{Name: "Shimmer Pad", Category: "Pad", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth, Detune: -5},
				Envelope1:      audio.Envelope{Attack: 150 * ms, Decay: 100 * ms, Sustain: 0.7, Release: 500 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Sawtooth, Detune: 5},
				Envelope2:      audio.Envelope{Attack: 150 * ms, Decay: 100 * ms, Sustain: 0.7, Release: 500 * ms},
				Mixer:          audio.Mixer{Volume1: 0.6, Volume2: 0.6},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.15},
				FilterEnvelope: audio.FilterEnvelope{Attack: 200 * ms, Decay: 250 * ms, Sustain: 0.35, Release: 500 * ms, Depth: 0.35},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 0.5, Depth: 0.15, Dest: audio.ModPitch},
			}},
		{Name: "Dream Pad", Category: "Pad",
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 120 * ms, Decay: 80 * ms, Sustain: 0.9, Release: 500 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Triangle},
				Envelope2:      audio.Envelope{Attack: 120 * ms, Decay: 80 * ms, Sustain: 0.7, Release: 500 * ms},
				Mixer:          audio.Mixer{Volume1: 0.6, Volume2: 0.5},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.45, Resonance: 0.05},
				FilterEnvelope: audio.FilterEnvelope{Attack: 150 * ms, Decay: 200 * ms, Sustain: 0.5, Release: 500 * ms, Depth: 0.35},
			}},
	}
}

func arpPatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "Chip Arp", Category: "Arp", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 30 * ms, Sustain: 0.7, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Tri Arp", Category: "Arp", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 40 * ms, Sustain: 0.8, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Pulse Arp 25%", Category: "Arp", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 25 * ms, Sustain: 0.7, Release: 15 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "DMG Arp", Category: "Arp", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 35 * ms, Sustain: 0.65, Release: 15 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "GB Fast Arp", Category: "Arp", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.25},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 20 * ms, Sustain: 0.5, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "SID Arp", Category: "Arp", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 50 * ms, Sustain: 0.5, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.6, Resonance: 0.3},
			}},
		{Name: "SID Hard Arp", Category: "Arp", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 40 * ms, Sustain: 0.6, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.55, Resonance: 0.5},
			}},
		{Name: "YM Arp", Category: "Arp", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.6, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Pluck Arp", Category: "Arp",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Bell Arp", Category: "Arp",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 120 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Bubble Arp", Category: "Arp",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 60 * ms, Sustain: 0.3, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.6, Resonance: 0.4},
			}},
		{Name: "Crystal Arp", Category: "Arp",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.65, Resonance: 0.3},
			}},
		{Name: "String Arp", Category: "Arp", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth, Detune: -6},
				Envelope1:   audio.Envelope{Attack: 10 * ms, Decay: 60 * ms, Sustain: 0.4, Release: 40 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Sawtooth, Detune: 6},
				Envelope2:   audio.Envelope{Attack: 10 * ms, Decay: 60 * ms, Sustain: 0.4, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 0.6, Volume2: 0.6},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.7, Resonance: 0.1},
			}},
		{Name: "Harp Arp", Category: "Arp", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sine},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Piano Arp", Category: "Arp", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 150 * ms, Sustain: 0.2, Release: 50 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Sine},
				Envelope2:   audio.Envelope{Attack: 3 * ms, Decay: 120 * ms, Sustain: 0.1, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 0.7, Volume2: 0.4},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
	}
}

func percussivePatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "NES Kick", Category: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Triangle},
				Envelope1:      audio.Envelope{Attack: 1 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 1 * ms, Decay: 50 * ms, Sustain: 0.0, Release: 20 * ms, Depth: 0.55},
			}},
		{Name: "NES Snare", Category: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 120 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "NES Hi-Hat", Category: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 30 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "NES Crash", Category: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 500 * ms, Sustain: 0.0, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Triangle Tom", Category: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Noise Tom", Category: "Percussive", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.2},
			}},
		{Name: "Gameboy Kick", Category: "Percussive", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 60 * ms, Sustain: 0.0, Release: 10 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Triangle},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 0.6, Volume2: 0.8},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Gameboy Snare", Category: "Percussive", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 15 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Gameboy Hi-Hat", Category: "Percussive", Tags: []string{"Gameboy"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 20 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "SID Noise Hit", Category: "Percussive", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.4, Resonance: 0.3},
			}},
		{Name: "Arcade Hit", Category: "Percussive", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.2},
			}},
		{Name: "Clap", Category: "Percussive",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 3 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.45, Resonance: 0.2},
			}},
		{Name: "Metallic", Category: "Percussive",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.55, Resonance: 0.4},
			}},
		{Name: "Sub Kick", Category: "Percussive", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 30 * ms, Depth: 0.5},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 0.8, Depth: 0.8, Dest: audio.ModPitch},
			}},
		{Name: "808 Kick", Category: "Percussive", Tags: []string{"Analog", "808"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 400 * ms, Sustain: 0.0, Release: 50 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.25, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 50 * ms, Depth: 0.55},
			}},
		{Name: "Snare", Category: "Percussive", Tags: []string{"Analog"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 30 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Triangle},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 50 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 0.7, Volume2: 0.4},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.35, Resonance: 0.1},
			}},
		{Name: "808 Snare", Category: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Noise},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 30 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Triangle},
				Envelope2:      audio.Envelope{Attack: 1 * ms, Decay: 60 * ms, Sustain: 0.0, Release: 15 * ms},
				Mixer:          audio.Mixer{Volume1: 0.8, Volume2: 0.5},
				Filter:         audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.35, Resonance: 0.2},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 60 * ms, Sustain: 0.0, Release: 30 * ms, Depth: 0.4},
			}},
		{Name: "808 Closed Hat", Category: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.0, Release: 8 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.65, Resonance: 0.1},
			}},
		{Name: "808 Open Hat", Category: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 400 * ms, Sustain: 0.0, Release: 60 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Noise},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 0.8, Volume2: 0.3},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.6, Resonance: 0.1},
			}},
		{Name: "808 Tom", Category: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 500 * ms, Sustain: 0.0, Release: 50 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.3, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 50 * ms, Depth: 0.5},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 2.5, Depth: 0.6, Dest: audio.ModPitch},
			}},
		{Name: "808 Cowbell", Category: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5, Detune: -15},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 250 * ms, Sustain: 0.0, Release: 30 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5, Detune: 15},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 250 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 0.6, Volume2: 0.6},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.62, Resonance: 0.5},
			}},
		{Name: "808 Clap", Category: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Noise},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.4, Resonance: 0.2},
				FilterEnvelope: audio.FilterEnvelope{Attack: 3 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 30 * ms, Depth: 0.35},
			}},
		{Name: "808 Cymbal", Category: "Percussive", Tags: []string{"808"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 800 * ms, Sustain: 0.0, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.55, Resonance: 0.15},
			}},
		{Name: "909 Kick", Category: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 220 * ms, Sustain: 0.0, Release: 30 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Noise},
				Envelope2:      audio.Envelope{Attack: 1 * ms, Decay: 25 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:          audio.Mixer{Volume1: 0.9, Volume2: 0.5},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.35, Resonance: 0.15},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 30 * ms, Depth: 0.5},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 5.0, Depth: 0.6, Dest: audio.ModPitch},
			}},
		{Name: "909 Snare", Category: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Noise},
				Envelope1:      audio.Envelope{Attack: 1 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 20 * ms},
				Oscillator2:    audio.Oscillator{Type: audio.Triangle},
				Envelope2:      audio.Envelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:          audio.Mixer{Volume1: 0.8, Volume2: 0.6},
				Filter:         audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.45, Resonance: 0.3},
				FilterEnvelope: audio.FilterEnvelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.0, Release: 20 * ms, Depth: 0.45},
			}},
		{Name: "909 Closed Hat", Category: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 15 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.75, Resonance: 0.1},
			}},
		{Name: "909 Open Hat", Category: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 250 * ms, Sustain: 0.0, Release: 40 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.72, Resonance: 0.1},
			}},
		{Name: "909 Clap", Category: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Noise},
				Envelope1:      audio.Envelope{Attack: 3 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.5, Resonance: 0.25},
				FilterEnvelope: audio.FilterEnvelope{Attack: 3 * ms, Decay: 50 * ms, Sustain: 0.0, Release: 20 * ms, Depth: 0.4},
			}},
		{Name: "909 Tom", Category: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sine},
				Envelope1:      audio.Envelope{Attack: 2 * ms, Decay: 300 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.4, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 2 * ms, Decay: 70 * ms, Sustain: 0.0, Release: 30 * ms, Depth: 0.45},
				LFO1:           audio.LFO{Waveform: audio.LFOSine, Rate: 4.0, Depth: 0.5, Dest: audio.ModPitch},
			}},
		{Name: "909 Cymbal", Category: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 700 * ms, Sustain: 0.0, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.6, Resonance: 0.15},
			}},
		{Name: "909 Rim", Category: "Percussive", Tags: []string{"909"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 50 * ms, Sustain: 0.0, Release: 8 * ms},
				Oscillator2: audio.Oscillator{Type: audio.Sine},
				Envelope2:   audio.Envelope{Attack: 1 * ms, Decay: 20 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:       audio.Mixer{Volume1: 0.7, Volume2: 0.4},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.65, Resonance: 0.3},
			}},
	}
}

func sfxPatches() []SynthPatch {
	ms := time.Millisecond
	return []SynthPatch{
		{Name: "Power Up", Category: "SFX", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 300 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSawtooth, Rate: 8.0, Depth: 0.5, Dest: audio.ModPitch},
			}},
		{Name: "Coin", Category: "SFX", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 80 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Jump", Category: "SFX", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 12.0, Depth: 0.3, Dest: audio.ModPitch},
			}},
		{Name: "Explosion", Category: "SFX", Tags: []string{"NES"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Noise},
				Envelope1:      audio.Envelope{Attack: 1 * ms, Decay: 400 * ms, Sustain: 0.0, Release: 50 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixNESPulse},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.2, Resonance: 0.1},
				FilterEnvelope: audio.FilterEnvelope{Attack: 1 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 50 * ms, Depth: 0.5},
			}},
		{Name: "SID Laser", Category: "SFX", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1:    audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:      audio.Envelope{Attack: 1 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:          audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:         audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.4, Resonance: 0.3},
				FilterEnvelope: audio.FilterEnvelope{Attack: 1 * ms, Decay: 150 * ms, Sustain: 0.0, Release: 20 * ms, Depth: 0.55},
				LFO1:           audio.LFO{Waveform: audio.LFOSawtooth, Rate: 10.0, Depth: 0.6, Dest: audio.ModPitch},
			}},
		{Name: "SID Zap", Category: "SFX", Tags: []string{"C64"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 100 * ms, Sustain: 0.0, Release: 15 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0, Mode: audio.MixSoftClip},
				Filter:      audio.Filter{Type: audio.FilterBandPass, Cutoff: 0.55, Resonance: 0.5},
			}},
		{Name: "Arcade Beep", Category: "SFX", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 60 * ms, Sustain: 0.0, Release: 10 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "UFO", Category: "SFX", Tags: []string{"Arcade"},
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Triangle},
				Envelope1:   audio.Envelope{Attack: 20 * ms, Decay: 50 * ms, Sustain: 0.8, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 15.0, Depth: 0.15, Dest: audio.ModPitch},
			}},
		{Name: "Sweep Up", Category: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 2 * ms, Decay: 300 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSawtooth, Rate: 5.0, Depth: 0.4, Dest: audio.ModPitch},
			}},
		{Name: "Alarm", Category: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Sustain: 0.8, Release: 50 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
				LFO1:        audio.LFO{Waveform: audio.LFOSquare, Rate: 4.0, Depth: 0.8, Dest: audio.ModVolume},
			}},
		{Name: "Blip", Category: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Square, PulseWidth: 0.5},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 40 * ms, Sustain: 0.0, Release: 5 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "White Noise", Category: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 10 * ms, Sustain: 0.8, Release: 100 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterOff},
			}},
		{Name: "Static Buzz", Category: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Noise},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Sustain: 0.7, Release: 80 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterHighPass, Cutoff: 0.5, Resonance: 0.1},
			}},
		{Name: "Glitch Hit", Category: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.NoisePeriodic},
				Envelope1:   audio.Envelope{Attack: 1 * ms, Decay: 120 * ms, Sustain: 0.0, Release: 20 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.5, Resonance: 0.3},
			}},
		{Name: "Wobble SFX", Category: "SFX",
			Synth: &audio.Synth{
				Oscillator1: audio.Oscillator{Type: audio.Sawtooth},
				Envelope1:   audio.Envelope{Attack: 5 * ms, Decay: 200 * ms, Sustain: 0.0, Release: 30 * ms},
				Mixer:       audio.Mixer{Volume1: 1.0},
				Filter:      audio.Filter{Type: audio.FilterLowPass, Cutoff: 0.6, Resonance: 0.4},
				LFO1:        audio.LFO{Waveform: audio.LFOSine, Rate: 8.0, Depth: 0.4, Dest: audio.ModCutoff},
			}},
	}
}
