// Package akwf embeds the AKWF-FREE single-cycle wavetable library.
// Call LoadAll to retrieve all ~4,800 waveforms.
//
// Waveforms are identified as "akwf:<bank>/<waveName>", e.g.:
//
//	akwf:AKWF_flute/AKWF_flute_0001
//
// Source: https://github.com/KristofferKarlAxelEkstrand/AKWF-FREE (CC0)
//
// The archive is generated by running: make compress
package akwf

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/json"
	"io"
	"log"
)

//go:embed akwf.tar.gz
var tarGzData []byte

// Entry describes a single waveform from the AKWF library.
type Entry struct {
	Bank string    // e.g. "AKWF_flute"
	Name string    // e.g. "AKWF_flute_0001"
	Data []float64 // one cycle of normalised samples
}

type manifest struct {
	Banks []string `json:"banks"`
}

// readArchive decompresses the embedded tar.gz and returns a map of
// bare filename → raw file bytes.
func readArchive() map[string][]byte {
	gr, err := gzip.NewReader(bytes.NewReader(tarGzData))
	if err != nil {
		log.Printf("akwf: gzip: %v", err)
		return nil
	}
	defer gr.Close()
	tr := tar.NewReader(gr)
	files := make(map[string][]byte)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Printf("akwf: tar: %v", err)
			return nil
		}
		data, err := io.ReadAll(tr)
		if err != nil {
			log.Printf("akwf: read %s: %v", hdr.Name, err)
			return nil
		}
		files[hdr.Name] = data
	}
	return files
}

// LoadAll reads the embedded manifest and all bank files, returning every
// waveform in a deterministic (manifest order, then alphabetical-within-bank)
// sequence.
func LoadAll() []Entry {
	files := readArchive()
	if files == nil {
		return nil
	}

	data, ok := files["manifest.json"]
	if !ok {
		log.Printf("akwf: manifest.json not found in archive")
		return nil
	}

	var m manifest
	if err := json.Unmarshal(data, &m); err != nil {
		log.Printf("akwf: cannot parse manifest.json: %v", err)
		return nil
	}

	var out []Entry
	for _, bank := range m.Banks {
		out = append(out, loadBank(files, bank)...)
	}
	return out
}

func loadBank(files map[string][]byte, bank string) []Entry {
	data, ok := files[bank+".json"]
	if !ok {
		// Not a fatal error — just skip missing banks.
		return nil
	}

	// Each JSON file is an object mapping waveform name → []float64.
	var waveforms map[string][]float64
	if err := json.Unmarshal(data, &waveforms); err != nil {
		return nil
	}

	// Preserve key order by building a sorted list.  The JSON keys are
	// already in alphabetical order in the source files; using a sorted
	// slice ensures a stable, deterministic order regardless of map
	// iteration.
	names := sortedKeys(waveforms)

	out := make([]Entry, len(names))
	for i, name := range names {
		out[i] = Entry{Bank: bank, Name: name, Data: waveforms[name]}
	}
	return out
}

// sortedKeys returns the keys of m in alphabetical order.
func sortedKeys(m map[string][]float64) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	// Simple insertion sort — at most ~100 elements per bank.
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && keys[j] < keys[j-1]; j-- {
			keys[j], keys[j-1] = keys[j-1], keys[j]
		}
	}
	return keys
}
